<html>

<head>
  <meta http-equiv="Content-Language" content="en-us">
  <meta name="keywords" content="animal angels foundation, animal angels, animal assisted therapy, therapy animals, therapet, animal assisted activities, trained therapy animals, trained animals, therapy pet, animal assisted therapy services, dog training services, animal angels foundation mumbai">
  <meta name="description" content="Animal Angels Foundation is the first organization in India practising in the field of animal-assisted therapy. Rohini Fernandes and Radhika Nair provide services like Animal Assisted Therapy, Dog Training, Trained Therapy Animals, Training Therapy Pets and more in Mumbai, India">
  <title>Home Page - Animal Angels Foundation is a Mumbai based Organization providing Animal Assisted Therapy</title>
  <link rel="stylesheet" type="text/css" href="/ds.css">
  <META HTTP-EQUIV="imagetoolbar" CONTENT="no">
  <script type="text/JavaScript" src="/common/javaScript/slideShow.js"></script>
  <script type="text/JavaScript" src="/common/javaScript/rightClick.js"></script>
  <script type="text/Javascript" src="/common/javaScript/dimensions.js"></script>
</head>

<body topmargin="0" leftmargin="0" bottommargin="0" rightmargin="0" onLoad="runSlideShow()" onResize="dimensions()">
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="779" id="AutoNumber1" height="100%" background="/images/bg-table.gif">
    <tr>
      <td width="779" valign="top" height="144">
      <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="779" id="AutoNumber2" height="144">
        <tr>
          <td width="779" height="22" valign="top">
            <?
              global $topNav;
              $topNav = "home";
              include($_SERVER['DOCUMENT_ROOT'] . "/common/top/menu.php");
            ?>
          </td>
        </tr>
        <tr>
          <td height="122" valign="top" width="779">
            <? include($_SERVER['DOCUMENT_ROOT'] . "/common/home/logo-mission.php"); ?>
          </td>
        </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td valign="top">
      <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="779" id="AutoNumber5" height="100%" background="/images/bg-left.gif">
        <tr>
          <td width="225" valign="top">
            <? include($_SERVER['DOCUMENT_ROOT'] . "/common/home/left-slide-show.php"); ?>
          </td>
          <td valign="top">
          <div align="center">
            <center>
            <script type="text/javascript">
              document.write("<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse\" bordercolor=\"#111111\" width=\"90%\" id=\"AutoNumber7\" height=" + tableHeight + ">");
            </script>
              <tr>
                <td width="100%" height="50">&nbsp;</td>
              </tr>
              <tr>
                <td width="100%">
                  <p align="justify"><b>Animal Angels Foundation</b> is a Mumbai based organization run by <b><a href="/meet-angels/rohini.php">Rohini Fernandes</a></b> and <b><a href="/meet-angels/radhika.php">Radhika Nair</a></b> who are clinical psychologists, certified practitioners of <a href="/about-aat/aat.php">animal-assisted therapy</a> and professional dog trainers.
                  <br /><br />
                  <table border="2" cellpadding="10" cellspacing="0" style="border-collapse: collapse" bordercolor="#fe9e3e" width="100%" id="FYSE">
                  <tr align="justify">
                    <td valign="top">
                      Rohini and Radhika have been chosen as part of the <a target="_blank" href="http://www.paragon100.asia/index.php/component/content/article/51-india/162-rohini-fernandes-and-radhika-nair">Paragon 100 Fellowship (2009-2010)</a> organised by The Foundation for Youth Social Entrepreneurship (FYSE). They are part of 100 young outstanding social change makers and entrepreneurs in the Asia Pacific region who dared to stride out by setting up their own business.
                    </td>
                  </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td width="100%" height="5">&nbsp;</td>
              </tr>
              <tr>
                <td>
                  <p align="justify"><b>Animal Angels Foundation</b> is the <b><i>first</i></b> organization in India working in the field of animal-assisted therapy.
                </td>
              </tr>
              <tr>
                <td width="100%" height="5">&nbsp;</td>
              </tr>
              <tr>
                <td><img src="/images/top-reel.jpg" width="500" height="15"></td>
              </tr>
              <tr>
		<td width="100%" height="80"><? include($_SERVER['DOCUMENT_ROOT'] . "/common/javaScript/scrollingMarquee.php"); ?></td>
	      </tr>
              <tr>
                <td><img src="/images/bottom-reel.jpg" width="500" height="15"></td>
              </tr>
              <tr>
                <td>
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="90%" id="AutoNumber8">
	            <tr align="center">
		      <td>
		        <div class="halfCurvy">
		          <em id="ctl"><b>&bull;</b></em>
                          <em id="cbl"><b>&bull;</b></em>
                          <em id="ctr"><b>&bull;</b></em>
                          <em id="cbr"><b>&bull;</b></em>
			    <p><center><b>Animal Angels featured in:</b></center>
			    <br />
			    <a href="/news/outlook-business.php">Outlook Business</a><br />
                            <a href="/news/afternoon.php">The Afternoon</a><br />
                            <a href="/news/outlook-india.php">Outlook India</a></p>
		        </div>
		      </td>
	            </tr>
	          </table>
                </td>
              </tr>


<!--
              <tr>
                <td width="100%" height="5">&nbsp;</td>
              </tr>
              <tr>
                <td>
                  <div align="center">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="90%" id="AutoNumber121">
                    <tr align="center">
                      <td width="100%">
                        <a href="http://www.mtvyouthicon.in.com/nominee.php?id=46636" target="_blank">
                        <p align="center"><img border="0" src="/images/mtv-youth-icon.jpg" alt="MTV Youth Icon banner" width="468" height="88"></p>
                        </a>
                      </td>
                   </tr>
                    <tr align="center">
                      <td width="100%" class="tch">
                        <p align="center"><span style="font-weight: 400">or in India just SMS "<b>Icon&nbsp;&nbsp;RO</b>" to 56882</span></p>
                      </td>
                   </tr>
                  </table>
                  </div>
                </td>
              </tr>
              <tr>
                <td width="100%" height="5">&nbsp;</td>
              </tr>
-->




<!--
              <tr>
                <td>
                  <div align="center">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="90%" id="AutoNumber8">
                    <tr align="center">
                      <td>
                        <br />
-->
<!--
                        <p><center><b>Register for our Canine First Aid Workshop!</b></center>
                        <br />
                        <a href="/angels-work/canine-workshop.php"><img border="0" src="/images/Canine_First_Aid_Thumbnail.jpg" alt="Canine First Aid Workshop Thumbnail" width="108" height="140"></a>
-->
<!--
                        <div class="halfCurvy">
                          <em id="ctl"><b>&bull;</b></em>
                          <em id="cbl"><b>&bull;</b></em>
                          <em id="ctr"><b>&bull;</b></em>
                          <em id="cbr"><b>&bull;</b></em>
                        <p><center><b>Animal Angels featured in</b></center><br />
                        <a href="/news/afternoon.php">The Afternoon</a><br />
                        <a href="/news/outlook-india.php">Outlook India</a></p>
                        </div>
                      </td>
                      <td>
                        <div class="halfCurvy">
                          <em id="ctl"><b>&bull;</b></em>
                          <em id="cbl"><b>&bull;</b></em>
                          <em id="ctr"><b>&bull;</b></em>
                          <em id="cbr"><b>&bull;</b></em>
                          <p><b>Check out our short films!</b><br>
			    <a href="/videos/vimeo.php">Vimeo</a><br />
                            <a href="/videos/youtube.php">You Tube</a><br />
                            <a href="/videos/mid-day.php">Interview with Mid-Day</a>
                          </p>
                        </div>
                      </td>
                    </tr>
                  </table>
                  </div>
                </td>
              </tr>
-->


              <tr>
                <td width="100%">
                  <p align="justify">Animal Angels Foundation was shortlisted by <a target="_blank" href="http://www.maricoinnovationfoundation.org/">Marico Innovation Foundation</a> as one of the top twenty-five innovations in India for the <a target="_blank" href="http://www.maricoinnovationfoundation.org/awards/pdfs/Social_Innovations.pdf">Innovation for India Awards 2007-2008</a>. Rohini and Radhika were also nominated as <a target="_blank" href="http://www.mtvyouthicon.in.com/nominee.php?id=46636">MTV Youth Icons of the year 2008</a> for their work at Animal Angels Foundation. We were nominated for the <a target="_blank" href="http://hotteststartups.in/viewandvote.do?method=fetch&businessFn=viewandvote&startupId=753">TATA NEN Startups Awards 2008</a>. Our organization was ranked <b>241 from 600</b> different startup companies in India!
                  <p align="justify">Through this therapy, our specially trained therapy pets assist us in helping children and adults learn or improve various skills and in speeding up the recovery process. We practice animal-assisted therapy in the areas of developmental disorders, psychiatric disorders, physical disabilities, physical illnesses and behavioural/emotional problems.
                </td>
              </tr>


              <tr>
                <td width="100%">
                  <p align="justify">We also work with kindergartens and schools where our therapy pets assist in educating children on how to interact with animals.
                  <p align="justify">We have a team of volunteers who along with their therapy dogs and cats do animal-assisted visits to places like orphanages and old age homes.

                  <p align="justify">Our therapy pets assist us in helping people cope with life's day-to-day challenges such as loss, stress, loneliness and illness, in learning new skills and in speeding up their recovery process.
                </td>
              </tr>

              <tr>
                <td width="100%">&nbsp;</td>
              </tr>
              <tr>

              <tr>
                <td>
                  <div align="center">
                  <table border="3" cellpadding="5" cellspacing="1" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber9">
                    <tr>
                      <td width="100%" class="tch">
                        <p align="justify"><span style="font-weight: 400">
		          <b>Animal Angels Foundation</b> is looking out for animal lovers who have done their M.A. in  clinical or counseling psychology and would like to join our team of angels in Mumbai. Please email us at <a href="mailto:animalangels@rediffmail.com">animalangels@rediffmail.com</a> with your details.</td>
                    </tr>
                   </table>
                   </div>
                 </td>
              </tr>

              <tr>
                <td width="100%">&nbsp;</td>
              </tr>
              <tr>
                <td width="100%">
                  <p align="center"><img border="0" src="/images/home-text.gif" alt="Quote by Ben Williams - There is no psychiatrist in the world like a puppy licking your face" width="478" height="93"></td>
              </tr>

              <tr>
                <td width="100%">&nbsp;</td>
              </tr>
            </table>
            </center>
          </div>

          <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="90%" id="AutoNumber9">
          <div align="center">

          <script type="text/Javascript" src="/common/javaScript/calculateHeight.js"></script>

          <?
            for ($i=1; $i<3; $i++)
            {
              print'<tr><td width="100%">&nbsp;</td></tr>' . "\n";
            }
	    if(stristr($_SERVER['SERVER_NAME'], 'animalangelsfoundation') == TRUE)
            {
                include($_SERVER['DOCUMENT_ROOT'] . "/common/bottom/google-analytics.php");
            }
            include($_SERVER['DOCUMENT_ROOT'] . "/common/bottom/rediffq&a.php");
          ?>



<h3><img border="0" src="/images/big-bullet.jpg" alt="Big bullet" align="absmiddle" width="20" height="18">&nbsp;&nbsp;We love hearing from you!</h3>
<?
require("/wordpress/wp-blog-header.php");
//require("/wordpress/wp-includes/query.php")
f?>


<!-- Start the Loop. -->
 <? query_posts($query_string . '&category_name=' .$topNav._.$leftNav. ''); ?>
 <? if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

 <!-- The following tests if the current post is in category 3. -->
 <!-- If it is, the div box is given the CSS class "post-cat-three". -->
 <!-- Otherwise, the div box will be given the CSS class "post". -->
 <div class="wp-caption">

 <!-- Display the Title as a link to the Post's permalink. -->
 <!-- h1><? the_title(); ?></h1 -->

 <!-- Display the date (November 16th, 2009 format) and a link to other posts by this posts author. -->
 <div class="who"><? the_author(); ?></div>
 <div class="timestamp">&nbsp;&nbsp;<? the_time('F jS, Y (g:i a)'); ?></div>
 <div class="commenzz"><? the_content(); ?></div>



<?
if ($post->comment_count)
{
//if($posts)
//{
//foreach($posts as $post) : setup_postdata($post);
$replies = mysql_fetch_assoc(mysql_query("SELECT comment_ID, comment_author, comment_content, comment_date FROM wp_comments WHERE comment_post_ID = '".$post->ID."' AND comment_approved = '1' ORDER BY comment_date DESC LIMIT 10"));;
?>
<ol>
 <div class="who"><? echo $replies['comment_author'] ?></div>
 <div class="timestamp">&nbsp;<? echo $replies['comment_date'] ?></div><br />
 <div class="commenzz"><? echo $replies['comment_content']; ?></div>
<?
//endforeach;
}
// }
?>


<ul class="commentlist">
<?php wp_list_comments('type=comment&callback=mytheme_comment'); ?>
</ul>

<?
//echo $comments;
//comments_template();
/*if (function_exists('have_comments')) :
echo Yaay;
else :
echo naay;
endif;
*/
//echo ( have_comments() );
if ( have_comments() ) :
echo Hello;
   while ( have_comments() ) :
         the_comment();
         $comment_post = get_post($comment->comment_post_ID);
   endwhile;
endif;
?>


<?php if ( have_comments() ) : ?>
<h3 id="comments"><?php comments_number('No Responses', 'One Response', '% Responses' );?> to “<?php the_title(); ?>”</h3>
<ol class="commentlist">
        <?php wp_list_comments(); ?>
        </ol>
<div class="navigation">
<div class="alignleft"><?php previous_comments_link() ?></div>
<div class="alignright"><?php next_comments_link() ?></div>
</div>

<?php else : // this is displayed if there are no comments so far ?>

        <?php if ('open' == $post->comment_status) : ?>
                <!-- If comments are open, but there are no comments. -->

        <?php else : // comments are closed ?>
                <!-- If comments are closed. -->
<p class="nocomments">Comments are closed.

        <?php endif; ?>
<?php endif; ?>



<?
        if ( have_comments() ) : ?>
	<h4 id="comments"><?php comments_number('No Comments', 'One Comment', '% Comments' );?></h4>
	 
	<ul class="commentlist">
	<?php wp_list_comments(); ?>
	</ul>
	 
	<div class="navigation">
	<div class="alignleft">< ?php previous_comments_link() ?></div>
	<div class="alignright">< ?php next_comments_link() ?></div>
	</div>
	<?php else : // this is displayed if there are no comments so far ?>
	    <?php if ('open' == $post->comment_status) :
	        // If comments are open, but there are no comments.
	    else : // comments are closed
	    endif;
	endif;
	?>



 <!-- Display a comma separated list of the Post's Categories. -->
 <!-- p class="postmetadata">Posted in <?php the_category(', '); ?></p -->
 </div> <!-- closes the first div box -->
 <hr align="left" width="95%" />
 <!-- Stop The Loop (but note the "else:" - see next line). -->
 <? endwhile; else: ?>

 <!-- The very first "if" tested to see if there were any Posts to -->
 <!-- display.  This "else" part tells what do if there weren't any. -->
 <p>Be the first to leave a comment!</p>

 <!-- REALLY stop The Loop. -->
 <? endif; ?>







          </div>
          </table>

          </td>
        </tr>
      </table>
      </td>
    </tr>
    <tr>
      <td width="779" valign="bottom" height="26">
        <? include($_SERVER['DOCUMENT_ROOT'] . "/common/bottom/footer.php"); ?>
      </td>
    </tr>
  </table>
  </center>
</div>
<script type="text/JavaScript" src="/common/javaScript/rollover.js"></script>

</body>

</html>
